TITLE_1: SCE0602
TITLE_2: Introdução à Ciência da Computação II
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SCE0602-Introducao-Ciencia-Da-Computacao-II
HERO_FILE: ciencia-computacao-ii.png